### ISSUE TITLE
Firefox version

### ISSUE THREAD

**Issue by pm64** [imdj/HNRelevant#5]
This extension is insanely useful. Would love to see a Firefox version, opening this issue to explore the possibility.

**Comment by imdj** [comment]
I've added the support for Firefox and submitted it as an add-on to https://addons.mozilla.org. Will update the README file when it's accepted.

**Comment by imdj** [comment]
It's now live on firefox addons 🥳
https://addons.mozilla.org/en-US/firefox/addon/hnrelevant/

Feel free to test it and report any issues
